[package]
name = "task4"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.8", features = ["provider-http", "rpc-types", "signer-local"] }
dotenvy = "0.15"
eyre = "0.6"
tokio = { version = "1", features = ["full"] }
