[package]
name = "task5"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.8", features = ["contract", "provider-http", "rpc-types"] }
dotenvy = "0.15"
eyre = "0.6"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
